
const cities = [
    { value : 'Aalen', label : 'Aalen' },
    { value : 'Bad Mergentheim', label : 'Bad Mergentheim' },
    { value : 'Baden-Baden', label : 'Baden-Baden' },
    { value : 'Bruchsal', label : 'Bruchsal' },
    { value : 'Esslingen', label : 'Esslingen' },
    { value : 'Freiburg im Breisgau', label : 'Freiburg im Breisgau' },
    { value : 'Freudenstadt', label : 'Freudenstadt' },
    { value : 'Friedrichshafen', label : 'Friedrichshafen' },
    { value : 'Göppingen', label : 'Göppingen' },
    { value : 'Hechingen', label : 'Hechingen' },
    { value : 'Heidelberg', label : 'Heidelberg' },
    { value : 'Heilbronn', label : 'Heilbronn' },
    { value : 'Karlsruhe', label : 'Karlsruhe' },
    { value : 'Konstanz', label : 'Konstanz' },
    { value : 'Ludwigsburg', label : 'Ludwigsburg' },
    { value : 'Mannheim', label : 'Mannheim' },
    { value : 'Offenburg', label : 'Offenburg' },
    { value : 'Pforzheim', label : 'Pforzheim' },
    { value : 'Ravensburg', label : 'Ravensburg' },
    { value : 'Reutlingen', label : 'Reutlingen' },
    { value : 'Schwäbisch Gmünd', label : 'Schwäbisch Gmünd' },
    { value : 'Schwäbisch Hall', label : 'Schwäbisch Hall' },
    { value : 'Stuttgart', label : 'Stuttgart' },
    { value : 'Tübingen', label : 'Tübingen' },
    { value : 'Ulm', label : 'Ulm' },
    { value : 'Amberg', label : 'Amberg' },
    { value : 'Ansbach', label : 'Ansbach' },
    { value : 'Aschaffenburg', label : 'Aschaffenburg' },
    { value : 'Augsburg', label : 'Augsburg' },
    { value : 'Bad Reichenhall', label : 'Bad Reichenhall' },
    { value : 'Bamberg', label : 'Bamberg' },
    { value : 'Bayreuth', label : 'Bayreuth' },
    { value : 'Berchtesgaden', label : 'Berchtesgaden' },
    { value : 'Coburg', label : 'Coburg' },
    { value : 'Dachau', label : 'Dachau' },
    { value : 'Deggendorf', label : 'Deggendorf' },
    { value : 'Dinkelsbühl', label : 'Dinkelsbühl' },
    { value : 'Donauwörth', label : 'Donauwörth' },
    { value : 'Erlangen', label : 'Erlangen' },
    { value : 'Freising', label : 'Freising' },
    { value : 'Fürth', label : 'Fürth' },
    { value : 'Füssen', label : 'Füssen' },
    { value : 'Garmisch-Partenkirchen', label : 'Garmisch-Partenkirchen' },
    { value : 'Ingolstadt', label : 'Ingolstadt' },
    { value : 'Kempten', label : 'Kempten' },
    { value : 'Landshut', label : 'Landshut' },
    { value : 'Lindau', label : 'Lindau' },
    { value : 'Memmingen', label : 'Memmingen' },
    { value : 'Mittenwald', label : 'Mittenwald' },
    { value : 'Munich', label : 'Munich' },
    { value : 'Nördlingen', label : 'Nördlingen' },
    { value : 'Nürnberg', label : 'Nürnberg' },
    { value : 'Passau', label : 'Passau' },
    { value : 'Regensburg', label : 'Regensburg' },
    { value : 'Rothenburg ob der Tauber', label : 'Rothenburg ob der Tauber' },
    { value : 'Würzburg', label : 'Würzburg' },
    { value : 'Advertisement', label : 'Advertisement' },
    { value : 'Berlin', label : 'Berlin' },
    { value : 'Charlottenburg (district)', label : 'Charlottenburg (district)' },
    { value : 'Spandau (area)', label : 'Spandau (area)' },
    { value : 'Tempelhof (area)', label : 'Tempelhof (area)' },
    { value : 'Tiergarten (area)', label : 'Tiergarten (area)' },
    { value : 'Brandenburg', label : 'Brandenburg' },
    { value : 'Brandenburg', label : 'Brandenburg' },
    { value : 'Cottbus', label : 'Cottbus' },
    { value : 'Eberswalde', label : 'Eberswalde' },
    { value : 'Frankfurt an der Oder', label : 'Frankfurt an der Oder' },
    { value : 'Potsdam', label : 'Potsdam' },
    { value : 'Schwedt', label : 'Schwedt' },
    { value : 'Bremen', label : 'Bremen' },
    { value : 'Bremerhaven', label : 'Bremerhaven' },
    { value : 'Hamburg', label : 'Hamburg' },
    { value : 'Altona', label : 'Altona' },
    { value : 'Bad Homburg', label : 'Bad Homburg' },
    { value : 'Darmstadt', label : 'Darmstadt' },
    { value : 'Frankfurt am Main', label : 'Frankfurt am Main' },
    { value : 'Fulda', label : 'Fulda' },
    { value : 'Giessen', label : 'Giessen' },
    { value : 'Hanau', label : 'Hanau' },
    { value : 'Kassel', label : 'Kassel' },
    { value : 'Lorsch', label : 'Lorsch' },
    { value : 'Marburg', label : 'Marburg' },
    { value : 'Offenbach', label : 'Offenbach' },
    { value : 'Rüdesheim', label : 'Rüdesheim' },
    { value : 'Wiesbaden', label : 'Wiesbaden' },
    { value : 'Bad Gandersheim', label : 'Bad Gandersheim' },
    { value : 'Bad Harzburg', label : 'Bad Harzburg' },
    { value : 'Braunschweig', label : 'Braunschweig' },
    { value : 'Celle', label : 'Celle' },
    { value : 'Cuxhaven', label : 'Cuxhaven' },
    { value : 'Delmenhorst', label : 'Delmenhorst' },
    { value : 'Emden', label : 'Emden' },
    { value : 'Goslar', label : 'Goslar' },
    { value : 'Göttingen', label : 'Göttingen' },
    { value : 'Hameln', label : 'Hameln' },
    { value : 'Hannover', label : 'Hannover' },
    { value : 'Helmstedt', label : 'Helmstedt' },
    { value : 'Hildesheim', label : 'Hildesheim' },
    { value : 'Lüneburg', label : 'Lüneburg' },
    { value : 'Oldenburg', label : 'Oldenburg' },
    { value : 'Osnabrück', label : 'Osnabrück' },
    { value : 'Salzgitter', label : 'Salzgitter' },
    { value : 'Stade', label : 'Stade' },
    { value : 'Wilhelmshaven', label : 'Wilhelmshaven' },
    { value : 'Wolfsburg', label : 'Wolfsburg' },
    { value : 'Greifswald', label : 'Greifswald' },
    { value : 'Güstrow', label : 'Güstrow' },
    { value : 'Neubrandenburg', label : 'Neubrandenburg' },
    { value : 'Peenemünde', label : 'Peenemünde' },
    { value : 'Rostock', label : 'Rostock' },
    { value : 'Schwerin', label : 'Schwerin' },
    { value : 'Stralsund', label : 'Stralsund' },
    { value : 'Wismar', label : 'Wismar' },
    { value : 'Aachen', label : 'Aachen' },
    { value : 'Arnsberg', label : 'Arnsberg' },
    { value : 'Bad Godesberg', label : 'Bad Godesberg' },
    { value : 'Bergisch Gladbach', label : 'Bergisch Gladbach' },
    { value : 'Bielefeld', label : 'Bielefeld' },
    { value : 'Bocholt', label : 'Bocholt' },
    { value : 'Bochum', label : 'Bochum' },
    { value : 'Bonn', label : 'Bonn' },
    { value : 'Bottrop', label : 'Bottrop' },
    { value : 'Brühl', label : 'Brühl' },
    { value : 'Castrop-Rauxel', label : 'Castrop-Rauxel' },
    { value : 'Cologne', label : 'Cologne' },
    { value : 'Detmold', label : 'Detmold' },
    { value : 'Dorsten', label : 'Dorsten' },
    { value : 'Dortmund', label : 'Dortmund' },
    { value : 'Duisburg', label : 'Duisburg' },
    { value : 'Düren', label : 'Düren' },
    { value : 'Düsseldorf', label : 'Düsseldorf' },
    { value : 'Essen', label : 'Essen' },
    { value : 'Gelsenkirchen', label : 'Gelsenkirchen' },
    { value : 'Gladbeck', label : 'Gladbeck' },
    { value : 'Gütersloh', label : 'Gütersloh' },
    { value : 'Hagen', label : 'Hagen' },
    { value : 'Hamm', label : 'Hamm' },
    { value : 'Herne', label : 'Herne' },
    { value : 'Hürth', label : 'Hürth' },
    { value : 'Iserlohn', label : 'Iserlohn' },
    { value : 'Jülich', label : 'Jülich' },
    { value : 'Kleve', label : 'Kleve' },
    { value : 'Königswinter', label : 'Königswinter' },
    { value : 'Krefeld', label : 'Krefeld' },
    { value : 'Leverkusen', label : 'Leverkusen' },
    { value : 'Lüdenscheid', label : 'Lüdenscheid' },
    { value : 'Lünen', label : 'Lünen' },
    { value : 'Marl', label : 'Marl' },
    { value : 'Minden', label : 'Minden' },
    { value : 'Moers', label : 'Moers' },
    { value : 'Mönchengladbach', label : 'Mönchengladbach' },
    { value : 'Mülheim an der Ruhr', label : 'Mülheim an der Ruhr' },
    { value : 'Münster', label : 'Münster' },
    { value : 'Neuss', label : 'Neuss' },
    { value : 'Paderborn', label : 'Paderborn' },
    { value : 'Recklinghausen', label : 'Recklinghausen' },
    { value : 'Remscheid', label : 'Remscheid' },
    { value : 'Rheine', label : 'Rheine' },
    { value : 'Siegen', label : 'Siegen' },
    { value : 'Soest', label : 'Soest' },
    { value : 'Solingen', label : 'Solingen' },
    { value : 'Wesel', label : 'Wesel' },
    { value : 'Witten', label : 'Witten' },
    { value : 'Wuppertal', label : 'Wuppertal' },
    { value : 'Bad Kreuznach', label : 'Bad Kreuznach' },
    { value : 'Bingen', label : 'Bingen' },
    { value : 'Boppard', label : 'Boppard' },
    { value : 'Frankenthal', label : 'Frankenthal' },
    { value : 'Kaiserslautern', label : 'Kaiserslautern' },
    { value : 'Koblenz', label : 'Koblenz' },
    { value : 'Landau', label : 'Landau' },
    { value : 'Ludwigshafen', label : 'Ludwigshafen' },
    { value : 'Mainz', label : 'Mainz' },
    { value : 'Neustadt an der Weinstrasse', label : 'Neustadt an der Weinstrasse' },
    { value : 'Speyer', label : 'Speyer' },
    { value : 'Trier', label : 'Trier' },
    { value : 'Worms', label : 'Worms' },
    { value : 'Saarland', label : 'Saarland' },
    { value : 'Homburg', label : 'Homburg' },
    { value : 'Reinheim', label : 'Reinheim' },
    { value : 'Saarbrücken', label : 'Saarbrücken' },
    { value : 'Saarlouis', label : 'Saarlouis' },
    { value : 'Saxony', label : 'Saxony' },
    { value : 'Altenburg', label : 'Altenburg' },
    { value : 'Annaberg-Buchholz', label : 'Annaberg-Buchholz' },
    { value : 'Bautzen', label : 'Bautzen' },
    { value : 'Chemnitz', label : 'Chemnitz' },
    { value : 'Dresden', label : 'Dresden' },
    { value : 'Freiberg', label : 'Freiberg' },
    { value : 'Görlitz', label : 'Görlitz' },
    { value : 'Hoyerswerda', label : 'Hoyerswerda' },
    { value : 'Leipzig', label : 'Leipzig' },
    { value : 'Meissen', label : 'Meissen' },
    { value : 'Torgau', label : 'Torgau' },
    { value : 'Zittau', label : 'Zittau' },
    { value : 'Zwickau', label : 'Zwickau' },
    { value : 'Bernburg', label : 'Bernburg' },
    { value : 'Dessau', label : 'Dessau' },
    { value : 'Eisleben', label : 'Eisleben' },
    { value : 'Halberstadt', label : 'Halberstadt' },
    { value : 'Halle', label : 'Halle' },
    { value : 'Köthen', label : 'Köthen' },
    { value : 'Merseburg', label : 'Merseburg' },
    { value : 'Naumburg', label : 'Naumburg' },
    { value : 'Quedlinburg', label : 'Quedlinburg' },
    { value : 'Stendal', label : 'Stendal' },
    { value : 'Wernigerode', label : 'Wernigerode' },
    { value : 'Wittenberg', label : 'Wittenberg' },
    { value : 'Büsum', label : 'Büsum' },
    { value : 'Eutin', label : 'Eutin' },
    { value : 'Flensburg', label : 'Flensburg' },
    { value : 'Glückstadt', label : 'Glückstadt' },
    { value : 'Kiel', label : 'Kiel' },
    { value : 'Lübeck', label : 'Lübeck' },
    { value : 'Rendsburg', label : 'Rendsburg' },
    { value : 'Schleswig', label : 'Schleswig' },
    { value : 'Thuringia', label : 'Thuringia' },
    { value : 'Arnstadt', label : 'Arnstadt' },
    { value : 'Eisenach', label : 'Eisenach' },
    { value : 'Erfurt', label : 'Erfurt' },
    { value : 'Gera', label : 'Gera' },
    { value : 'Gotha', label : 'Gotha' },
    { value : 'Jena', label : 'Jena' },
    { value : 'Meiningen', label : 'Meiningen' },
    { value : 'Mühlhausen', label : 'Mühlhausen' },
    { value : 'Nordhausen', label : 'Nordhausen' },
    { value : 'Suhl', label : 'Suhl' },
    { value : 'Weimar', label : 'Weimar' }
];

export default cities;